"""Cross-seed sim-to-real summary analysis for actuator model evaluations.

This script aggregates per-seed evaluation outputs generated by
`sim2real_evaluation.py` and produces:

1) Velocity comparison across trajectories using cross-seed sim mean and +-1 sigma band.

2) RMSE distribution boxplots across seeds for each trajectory:
    - RMSE X
    - RMSE Y
    - Combined speed RMSE

3) Machine-readable summary exports:
    - JSON with aggregate statistics
    - JSON with seed/trajectory metrics and trajectory-level stats

Example:
    # Combined subplot figures (default, matches the original layout)
    python scripts/actuator_model/sim2real_seed_analysis.py \
        logs/actuator_model/data/evaluation/new/from_new_model

    # One velocity-comparison PNG per trajectory (RMSE boxplot stays a
    # single figure regardless of --separate)
    python scripts/actuator_model/sim2real_seed_analysis.py \
        logs/actuator_model/data/evaluation/new/from_new_model --separate
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Patch

from sim2real_evaluation import (
    draw_velocity_comparison,
    finalize_combined_grid_legend,
    load_trajectory_arrays,
    make_combined_grid,
    save_figure,
)


def natural_sort_key(text: str) -> list[Any]:
    """Sort strings with embedded numbers naturally."""
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", text)]


def trajectory_sort_key(name: str) -> tuple[int, str]:
    """Prefer sorting by trailing integer in trajectory filename."""
    stem = Path(name).stem
    match = re.search(r"(\d+)$", stem)
    if match:
        return (int(match.group(1)), name)
    return (10**9, name)


def load_seed_record(seed_dir: Path) -> dict[str, Any]:
    """Load metrics, derived speed RMSE, and trajectory signals for one seed."""
    metrics_path = seed_dir / "sim2real_evaluation_metrics.json"
    if not metrics_path.exists():
        raise FileNotFoundError(f"Missing metrics file: {metrics_path}")

    metrics_json = json.loads(metrics_path.read_text())
    traj_metrics = metrics_json.get("trajectories", {})
    if not isinstance(traj_metrics, dict) or not traj_metrics:
        raise ValueError(f"No trajectory metrics found in {metrics_path}")

    npz_files = sorted(seed_dir.glob("*.npz"), key=lambda p: trajectory_sort_key(p.name))
    if not npz_files:
        raise FileNotFoundError(f"No trajectory .npz files found in {seed_dir}")

    rmse_speed_by_traj: dict[str, float] = {}
    sim_vel_by_traj: dict[str, dict[str, np.ndarray]] = {}
    real_vel_by_traj: dict[str, dict[str, np.ndarray]] = {}
    action_by_traj: dict[str, dict[str, np.ndarray]] = {}
    for npz_file in npz_files:
        arr = load_trajectory_arrays(npz_file)
        sim_vel_by_traj[npz_file.name] = {"x": arr["vel_sim_x"], "y": arr["vel_sim_y"]}
        real_vel_by_traj[npz_file.name] = {"x": arr["vel_real_x"], "y": arr["vel_real_y"]}
        action_by_traj[npz_file.name] = {"x": arr["action_x"], "y": arr["action_y"]}
        err_x = arr["vel_sim_x"] - arr["vel_real_x"]
        err_y = arr["vel_sim_y"] - arr["vel_real_y"]
        rmse_speed_by_traj[npz_file.name] = float(np.sqrt(np.mean(err_x**2 + err_y**2)))

    metrics_traj_names = set(traj_metrics.keys())
    npz_traj_names = set(sim_vel_by_traj.keys())
    common_traj_names = sorted(metrics_traj_names & npz_traj_names, key=trajectory_sort_key)
    if not common_traj_names:
        raise ValueError(f"No overlapping trajectory names between JSON and NPZ in {seed_dir}")

    missing_in_npz = sorted(metrics_traj_names - npz_traj_names, key=trajectory_sort_key)
    missing_in_metrics = sorted(npz_traj_names - metrics_traj_names, key=trajectory_sort_key)
    if missing_in_npz:
        print(f"[WARN] {seed_dir.name}: trajectories in JSON but not NPZ: {missing_in_npz}")
    if missing_in_metrics:
        print(f"[WARN] {seed_dir.name}: trajectories in NPZ but not JSON: {missing_in_metrics}")

    rmse_xy_by_traj: dict[str, dict[str, float]] = {}
    for traj_name in common_traj_names:
        entry = traj_metrics[traj_name]
        try:
            rmse_x = float(entry["rmse_x"])
            rmse_y = float(entry["rmse_y"])
        except KeyError as exc:
            raise KeyError(f"Missing key {exc} for trajectory {traj_name} in {metrics_path}") from exc
        rmse_xy_by_traj[traj_name] = {"rmse_x": rmse_x, "rmse_y": rmse_y}

    return {
        "seed": seed_dir.name,
        "seed_dir": seed_dir,
        "rmse_xy_by_traj": rmse_xy_by_traj,
        "rmse_speed_by_traj": {k: rmse_speed_by_traj[k] for k in common_traj_names},
        "sim_vel_by_traj": {k: sim_vel_by_traj[k] for k in common_traj_names},
        "real_vel_by_traj": {k: real_vel_by_traj[k] for k in common_traj_names},
        "action_by_traj": {k: action_by_traj[k] for k in common_traj_names},
    }


def discover_seed_dirs(root_dir: Path, pattern: str) -> list[Path]:
    """Find seed directories and return them in natural order."""
    seed_dirs = sorted([p for p in root_dir.glob(pattern) if p.is_dir()], key=lambda p: natural_sort_key(p.name))
    return seed_dirs


def compute_distribution_stats(values: list[float]) -> dict[str, float]:
    """Return standard summary statistics for one distribution."""
    arr = np.asarray(values, dtype=float)
    q25 = float(np.percentile(arr, 25))
    q75 = float(np.percentile(arr, 75))
    return {
        "mean": float(np.mean(arr)),
        "sigma": float(np.std(arr)),
        "median": float(np.median(arr)),
        "min": float(np.min(arr)),
        "max": float(np.max(arr)),
        "q25": q25,
        "q75": q75,
        "iqr": float(q75 - q25),
    }


def build_aggregate(seed_records: list[dict[str, Any]]) -> dict[str, Any]:
    """Aggregate trajectory-level and seed-level metrics across all seeds."""
    if not seed_records:
        raise ValueError("No seed records to aggregate")

    common_trajs = set(seed_records[0]["rmse_xy_by_traj"].keys())
    for record in seed_records[1:]:
        common_trajs &= set(record["rmse_xy_by_traj"].keys())
    common_traj_names = sorted(common_trajs, key=trajectory_sort_key)
    if not common_traj_names:
        raise ValueError("No common trajectories found across seeds")

    dropped_info: list[dict[str, Any]] = []
    for record in seed_records:
        traj_names = set(record["rmse_xy_by_traj"].keys())
        dropped = sorted(traj_names - set(common_traj_names), key=trajectory_sort_key)
        if dropped:
            dropped_info.append({"seed": record["seed"], "dropped_trajectories": dropped})

    values_by_traj = {traj: {"rmse_x": [], "rmse_y": [], "rmse_speed": []} for traj in common_traj_names}
    seed_level_summary: dict[str, dict[str, float]] = {}

    for record in seed_records:
        seed_name = record["seed"]
        rmse_x_vals = []
        rmse_y_vals = []
        rmse_speed_vals = []
        for traj in common_traj_names:
            rmse_x = float(record["rmse_xy_by_traj"][traj]["rmse_x"])
            rmse_y = float(record["rmse_xy_by_traj"][traj]["rmse_y"])
            rmse_speed = float(record["rmse_speed_by_traj"][traj])

            values_by_traj[traj]["rmse_x"].append(rmse_x)
            values_by_traj[traj]["rmse_y"].append(rmse_y)
            values_by_traj[traj]["rmse_speed"].append(rmse_speed)

            rmse_x_vals.append(rmse_x)
            rmse_y_vals.append(rmse_y)
            rmse_speed_vals.append(rmse_speed)

        seed_level_summary[seed_name] = {
            "mean_rmse_x": float(np.mean(rmse_x_vals)),
            "mean_rmse_y": float(np.mean(rmse_y_vals)),
            "mean_rmse_speed": float(np.mean(rmse_speed_vals)),
        }

    traj_stats: dict[str, dict[str, dict[str, float]]] = {}
    all_rmse_x: list[float] = []
    all_rmse_y: list[float] = []
    all_rmse_speed: list[float] = []

    for traj in common_traj_names:
        x_vals = values_by_traj[traj]["rmse_x"]
        y_vals = values_by_traj[traj]["rmse_y"]
        s_vals = values_by_traj[traj]["rmse_speed"]

        all_rmse_x.extend(x_vals)
        all_rmse_y.extend(y_vals)
        all_rmse_speed.extend(s_vals)

        traj_stats[traj] = {
            "rmse_x": compute_distribution_stats(x_vals),
            "rmse_y": compute_distribution_stats(y_vals),
            "rmse_speed": compute_distribution_stats(s_vals),
        }

    overall_stats = {
        "rmse_x": compute_distribution_stats(all_rmse_x),
        "rmse_y": compute_distribution_stats(all_rmse_y),
        "rmse_speed": compute_distribution_stats(all_rmse_speed),
    }

    temporal_by_traj: dict[str, dict[str, Any]] = {}
    reference_by_traj: dict[str, dict[str, np.ndarray]] = {}
    for traj in common_traj_names:
        seed_arrays_x: list[np.ndarray] = []
        seed_arrays_y: list[np.ndarray] = []
        for record in seed_records:
            seed_arrays_x.append(np.asarray(record["sim_vel_by_traj"][traj]["x"], dtype=float))
            seed_arrays_y.append(np.asarray(record["sim_vel_by_traj"][traj]["y"], dtype=float))

        min_len = min(arr.shape[0] for arr in seed_arrays_x)
        if min_len <= 0:
            raise ValueError(f"Trajectory {traj} has empty velocity arrays")

        stack_x = np.stack([arr[:min_len] for arr in seed_arrays_x], axis=0)
        stack_y = np.stack([arr[:min_len] for arr in seed_arrays_y], axis=0)

        temporal_by_traj[traj] = {
            "time_steps": np.arange(min_len, dtype=int),
            "mean_x": np.mean(stack_x, axis=0),
            "sigma_x": np.std(stack_x, axis=0),
            "mean_y": np.mean(stack_y, axis=0),
            "sigma_y": np.std(stack_y, axis=0),
            "min_length_across_seeds": int(min_len),
        }

        # Keep commanded and real traces from the first valid seed as reference lines.
        ref_record = seed_records[0]
        ref_action_x = np.asarray(ref_record["action_by_traj"][traj]["x"], dtype=float)
        ref_action_y = np.asarray(ref_record["action_by_traj"][traj]["y"], dtype=float)
        ref_real_x = np.asarray(ref_record["real_vel_by_traj"][traj]["x"], dtype=float)
        ref_real_y = np.asarray(ref_record["real_vel_by_traj"][traj]["y"], dtype=float)
        reference_by_traj[traj] = {
            "action_x": ref_action_x[:min_len],
            "action_y": ref_action_y[:min_len],
            "real_x": ref_real_x[:min_len],
            "real_y": ref_real_y[:min_len],
        }

    return {
        "seed_names": [record["seed"] for record in seed_records],
        "trajectory_names": common_traj_names,
        "dropped_trajectories": dropped_info,
        "values_by_traj": values_by_traj,
        "trajectory_stats": traj_stats,
        "seed_level_summary": seed_level_summary,
        "overall_stats": overall_stats,
        "temporal_by_traj": temporal_by_traj,
        "reference_by_traj": reference_by_traj,
    }


def _draw_velocity_comparison_with_sigma(ax, traj_index, temporal, ref):
    draw_velocity_comparison(
        ax,
        np.asarray(temporal["time_steps"], dtype=int),
        ref["action_x"],
        ref["action_y"],
        ref["real_x"],
        ref["real_y"],
        np.asarray(temporal["mean_x"], dtype=float),
        np.asarray(temporal["mean_y"], dtype=float),
        sim_x_sigma=np.asarray(temporal["sigma_x"], dtype=float),
        sim_y_sigma=np.asarray(temporal["sigma_y"], dtype=float),
        title=f"Trajectory {traj_index + 1}",
    )


def plot_velocity_comparison_with_sigma(
    aggregate: dict[str, Any], output_dir: Path, dpi: int, separate: bool = False
) -> Path | list[Path]:
    """Plot original-style velocity comparison with sim mean +- 1σ bands."""
    traj_names = aggregate["trajectory_names"]
    temporal_by_traj = aggregate["temporal_by_traj"]
    reference_by_traj = aggregate["reference_by_traj"]

    suptitle = "Sim-to-Real Actuator Model Validation"

    if separate:
        out_paths: list[Path] = []
        for i, traj in enumerate(traj_names):
            fig, ax = plt.subplots(figsize=(9, 5), constrained_layout=True)
            fig.suptitle(suptitle, fontsize=13, weight="bold")
            _draw_velocity_comparison_with_sigma(ax, i, temporal_by_traj[traj], reference_by_traj[traj])
            ax.legend(loc="best", fontsize=8)
            slug = Path(traj).stem
            name = f"sim2real_seed_summary_01_velocity_comparison_with_sigma_{slug}.png"
            save_figure(fig, name, output_dir, dpi=dpi)
            plt.close(fig)
            out_paths.append(output_dir / name)
        return out_paths

    n_traj = len(traj_names)
    fig, ax_flat = make_combined_grid(n_traj, suptitle)

    for i, traj in enumerate(traj_names):
        _draw_velocity_comparison_with_sigma(ax_flat[i], i, temporal_by_traj[traj], reference_by_traj[traj])

    finalize_combined_grid_legend(ax_flat, n_traj, legend_fontsize=10)

    name = "sim2real_seed_summary_01_velocity_comparison_with_sigma.png"
    save_figure(fig, name, output_dir, dpi=dpi)
    plt.close(fig)
    return output_dir / name


def _draw_velocity_rmse_boxplot(ax, n_traj, rmse_speed_data):
    """Draw the per-trajectory velocity-RMSE boxplot onto ax."""
    centers = np.arange(n_traj)
    color = "green"

    box = ax.boxplot(
        rmse_speed_data,
        positions=centers,
        widths=0.5,
        patch_artist=True,
        showfliers=False,
        medianprops={"color": "black", "linewidth": 1.4},
        whiskerprops={"color": color, "linewidth": 1.1},
        capprops={"color": color, "linewidth": 1.1},
    )
    for patch in box["boxes"]:
        patch.set_facecolor(color)
        patch.set_alpha(0.35)
        patch.set_edgecolor(color)

    rng = np.random.default_rng(42)
    for pos, vals in zip(centers, rmse_speed_data):
        vals_arr = np.asarray(vals, dtype=float)
        jitter = rng.uniform(-0.08, 0.08, size=vals_arr.shape[0])
        ax.scatter(
            np.full(vals_arr.shape[0], pos) + jitter,
            vals_arr,
            marker="x",
            color=color,
            linewidths=1.0,
            s=36,
            alpha=0.85,
            zorder=3,
        )

    ax.set_xticks(centers)
    ax.set_xticklabels([str(i + 1) for i in range(n_traj)])
    ax.set_xlabel("Trajectory")
    ax.set_ylabel("Velocity RMSE (m/s)")
    ax.grid(True, linestyle=":", alpha=0.6, axis="y")

    legend_handles = [Patch(facecolor=color, edgecolor=color, alpha=0.35, label="Velocity RMSE")]
    ax.legend(handles=legend_handles, loc="upper right")


def plot_rmse_distributions(aggregate: dict[str, Any], output_dir: Path, dpi: int) -> Path:
    """Plot velocity-RMSE boxplots (one per trajectory) across seeds."""
    traj_names = aggregate["trajectory_names"]
    values_by_traj = aggregate["values_by_traj"]
    rmse_speed_data = [values_by_traj[traj]["rmse_speed"] for traj in traj_names]
    n_traj = len(traj_names)

    fig_width = max(8, 1.0 * n_traj + 3)
    fig, ax = plt.subplots(figsize=(fig_width, 6), constrained_layout=True)
    fig.suptitle("Cross-Seed Velocity RMSE Distribution by Trajectory", fontsize=16, weight="bold")

    _draw_velocity_rmse_boxplot(ax, n_traj, rmse_speed_data)

    name = "sim2real_seed_summary_02_rmse_distributions.png"
    save_figure(fig, name, output_dir, dpi=dpi)
    plt.close(fig)
    return output_dir / name


def plot_combined(aggregate: dict[str, Any], output_dir: Path, dpi: int) -> Path:
    """Combined figure: cross-seed velocity comparison panels + RMSE boxplot stacked vertically."""
    traj_names = aggregate["trajectory_names"]
    temporal_by_traj = aggregate["temporal_by_traj"]
    reference_by_traj = aggregate["reference_by_traj"]
    values_by_traj = aggregate["values_by_traj"]

    n_traj = len(traj_names)
    legend_row_h = 0.8
    vel_row_h = 3.0
    box_row_h = 4.0
    width = 7.0

    fig = plt.figure(figsize=(width, legend_row_h + vel_row_h * n_traj + box_row_h), constrained_layout=True)
    fig.suptitle(
        "Sim-to-Real Actuator Model Validation",
        fontsize=18,
        weight="bold",
    )

    gs = fig.add_gridspec(n_traj + 2, 1, height_ratios=[legend_row_h] + [vel_row_h] * n_traj + [box_row_h])

    # Top gridspec row: dedicated slot for the shared horizontal legend.
    legend_ax = fig.add_subplot(gs[0, 0])
    legend_ax.axis("off")

    vel_axes = []
    for i, traj in enumerate(traj_names):
        ax = fig.add_subplot(gs[1 + i, 0])
        _draw_velocity_comparison_with_sigma(ax, i, temporal_by_traj[traj], reference_by_traj[traj])
        vel_axes.append(ax)

    handles, labels = vel_axes[0].get_legend_handles_labels()
    label_to_handle = dict(zip(labels, handles))
    desired_rows = [
        ["Commanded Vel X", "Real Vel X", "Sim Vel X (mean)", "Sim Vel X ±1σ"],
        ["Commanded Vel Y", "Real Vel Y", "Sim Vel Y (mean)", "Sim Vel Y ±1σ"],
    ]
    n_rows = len(desired_rows)
    n_cols = len(desired_rows[0])
    # Matplotlib fills legends column-major; supply items column-by-column to render row-major.
    ordered_labels = [desired_rows[r][c] for c in range(n_cols) for r in range(n_rows)]
    ordered_handles = [label_to_handle[lbl] for lbl in ordered_labels]
    legend_ax.legend(ordered_handles, ordered_labels, loc="center", ncol=n_cols, fontsize=9)

    box_ax = fig.add_subplot(gs[n_traj + 1, 0])
    rmse_speed_data = [values_by_traj[traj]["rmse_speed"] for traj in traj_names]
    _draw_velocity_rmse_boxplot(box_ax, n_traj, rmse_speed_data)

    name = "sim2real_seed_summary_combined.png"
    save_figure(fig, name, output_dir, dpi=dpi)
    plt.close(fig)
    return output_dir / name


def write_seed_traj_metrics_json(aggregate: dict[str, Any], output_dir: Path) -> Path:
    """Write long-format seed/trajectory metric table as JSON."""
    traj_names = aggregate["trajectory_names"]
    seed_names = aggregate["seed_names"]
    values_by_traj = aggregate["values_by_traj"]

    rows: list[dict[str, Any]] = []
    for traj in traj_names:
        x_vals = values_by_traj[traj]["rmse_x"]
        y_vals = values_by_traj[traj]["rmse_y"]
        s_vals = values_by_traj[traj]["rmse_speed"]
        for seed, rmse_x, rmse_y, rmse_speed in zip(seed_names, x_vals, y_vals, s_vals):
            rows.append({
                "seed": seed,
                "trajectory": traj,
                "rmse_x": float(rmse_x),
                "rmse_y": float(rmse_y),
                "rmse_speed": float(rmse_speed),
            })

    out_path = output_dir / "sim2real_seed_summary_seed_trajectory_metrics.json"
    out_path.write_text(json.dumps({"rows": rows}, indent=2))
    print(f"Saved JSON to {out_path}")
    return out_path


def write_traj_stats_json(aggregate: dict[str, Any], output_dir: Path) -> Path:
    """Write trajectory-level summary statistics table as JSON."""
    rows: list[dict[str, Any]] = []
    for traj in aggregate["trajectory_names"]:
        for metric in ["rmse_x", "rmse_y", "rmse_speed"]:
            stats = aggregate["trajectory_stats"][traj][metric]
            rows.append({
                "trajectory": traj,
                "metric": metric,
                "mean": float(stats["mean"]),
                "sigma": float(stats["sigma"]),
                "median": float(stats["median"]),
                "min": float(stats["min"]),
                "max": float(stats["max"]),
                "q25": float(stats["q25"]),
                "q75": float(stats["q75"]),
                "iqr": float(stats["iqr"]),
            })

    out_path = output_dir / "sim2real_seed_summary_trajectory_stats.json"
    out_path.write_text(json.dumps({"rows": rows}, indent=2))
    print(f"Saved JSON to {out_path}")
    return out_path


def write_summary_json(aggregate: dict[str, Any], root_dir: Path, output_dir: Path) -> Path:
    """Write complete aggregate summary as JSON."""
    out_path = output_dir / "sim2real_seed_summary_metrics.json"

    summary = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "input_root": str(root_dir),
        "seed_names": aggregate["seed_names"],
        "trajectory_names": aggregate["trajectory_names"],
        "dropped_trajectories": aggregate["dropped_trajectories"],
        "overall_stats": aggregate["overall_stats"],
        "seed_level_summary": aggregate["seed_level_summary"],
        "trajectory_stats": aggregate["trajectory_stats"],
        "trajectory_values": aggregate["values_by_traj"],
        "temporal_min_lengths": {
            traj: int(aggregate["temporal_by_traj"][traj]["min_length_across_seeds"])
            for traj in aggregate["trajectory_names"]
        },
    }

    out_path.write_text(json.dumps(summary, indent=2))
    print(f"Saved JSON to {out_path}")
    return out_path


def print_console_summary(aggregate: dict[str, Any]) -> None:
    """Print concise summary and outlier hints to stdout."""
    print("\nCross-seed summary:")
    print(f"  Seeds used: {len(aggregate['seed_names'])} -> {aggregate['seed_names']}")
    print(f"  Common trajectories: {len(aggregate['trajectory_names'])}")

    overall = aggregate["overall_stats"]
    print(
        "  Overall mean RMSE "
        f"X={overall['rmse_x']['mean']:.6f}, "
        f"Y={overall['rmse_y']['mean']:.6f}, "
        f"Speed={overall['rmse_speed']['mean']:.6f}"
    )

    traj_rank_x = sorted(aggregate["trajectory_stats"].items(), key=lambda kv: kv[1]["rmse_x"]["median"], reverse=True)
    traj_rank_y = sorted(aggregate["trajectory_stats"].items(), key=lambda kv: kv[1]["rmse_y"]["median"], reverse=True)
    traj_rank_speed = sorted(
        aggregate["trajectory_stats"].items(), key=lambda kv: kv[1]["rmse_speed"]["median"], reverse=True
    )

    worst_x = traj_rank_x[0]
    worst_y = traj_rank_y[0]
    worst_s = traj_rank_speed[0]
    print(
        "  Highest median RMSE trajectories: "
        f"X={worst_x[0]} ({worst_x[1]['rmse_x']['median']:.6f}), "
        f"Y={worst_y[0]} ({worst_y[1]['rmse_y']['median']:.6f}), "
        f"Speed={worst_s[0]} ({worst_s[1]['rmse_speed']['median']:.6f})"
    )

    seed_rank_x = sorted(aggregate["seed_level_summary"].items(), key=lambda kv: kv[1]["mean_rmse_x"], reverse=True)
    seed_rank_y = sorted(aggregate["seed_level_summary"].items(), key=lambda kv: kv[1]["mean_rmse_y"], reverse=True)
    seed_rank_s = sorted(aggregate["seed_level_summary"].items(), key=lambda kv: kv[1]["mean_rmse_speed"], reverse=True)
    print(
        "  Highest seed means: "
        f"X={seed_rank_x[0][0]} ({seed_rank_x[0][1]['mean_rmse_x']:.6f}), "
        f"Y={seed_rank_y[0][0]} ({seed_rank_y[0][1]['mean_rmse_y']:.6f}), "
        f"Speed={seed_rank_s[0][0]} ({seed_rank_s[0][1]['mean_rmse_speed']:.6f})"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Aggregate sim2real evaluation results across multiple seed folders.")
    parser.add_argument(
        "evaluation_root",
        type=Path,
        help="Directory containing seed subfolders (e.g., seed0..seed7)",
    )
    parser.add_argument(
        "--seed_pattern",
        type=str,
        default="seed*",
        help="Glob pattern to discover seed directories (default: seed*)",
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        default=None,
        help="Output directory for plots and summaries (default: evaluation_root)",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=150,
        help="Figure DPI (default: 150)",
    )
    layout_group = parser.add_mutually_exclusive_group()
    layout_group.add_argument(
        "--separate",
        action="store_true",
        help=(
            "Emit the per-trajectory velocity comparison panels as individual PNGs "
            "instead of one combined subplot figure. The RMSE distribution plot is "
            "always a single figure."
        ),
    )
    layout_group.add_argument(
        "--combine",
        action="store_true",
        help=(
            "Emit a single PNG with the velocity comparison subplots above and the "
            "RMSE boxplot stacked beneath. Mutually exclusive with --separate."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root_dir = args.evaluation_root
    output_dir = args.output_dir or root_dir

    if not root_dir.exists() or not root_dir.is_dir():
        raise SystemExit(f"Invalid evaluation root: {root_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)

    seed_dirs = discover_seed_dirs(root_dir, args.seed_pattern)
    if not seed_dirs:
        raise SystemExit(f"No seed directories found in {root_dir} using pattern '{args.seed_pattern}'")

    print(f"Discovered {len(seed_dirs)} seed folders: {[p.name for p in seed_dirs]}")

    seed_records: list[dict[str, Any]] = []
    for seed_dir in seed_dirs:
        try:
            seed_records.append(load_seed_record(seed_dir))
        except Exception as exc:
            print(f"[WARN] Skipping {seed_dir.name}: {exc}")

    if len(seed_records) < 2:
        raise SystemExit("Need at least two valid seed folders for cross-seed analysis")

    aggregate = build_aggregate(seed_records)

    if args.combine:
        plot_combined(aggregate, output_dir, dpi=args.dpi)
    else:
        plot_velocity_comparison_with_sigma(aggregate, output_dir, dpi=args.dpi, separate=args.separate)
        plot_rmse_distributions(aggregate, output_dir, dpi=args.dpi)

    write_summary_json(aggregate, root_dir, output_dir)
    write_seed_traj_metrics_json(aggregate, output_dir)
    write_traj_stats_json(aggregate, output_dir)

    print_console_summary(aggregate)


if __name__ == "__main__":
    main()
