#!/usr/bin/env python3
"""Train Klask agent with FastSAC + HER on GPU using IsaacLab (PhysX).

Fork of train_fast_sac.py that uses IsaacLab's ManagerBasedRLEnv instead of
MuJoCo Warp. The algorithm, networks, and buffer are identical.

Usage:
    python scripts/train_fast_sac_isaaclab.py --num-envs 4096
    python scripts/train_fast_sac_isaaclab.py --num-envs 4096 --her-ratio 0.9
"""

# =============================================================================
# Phase 1: AppLauncher must run before any IsaacLab / USD / warp imports.
# =============================================================================

from __future__ import annotations

import argparse
import sys

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(
    description="Train FastSAC+HER with IsaacLab.",
    # Allow unknown args so tyro can parse the rest.
    allow_abbrev=False,
)
AppLauncher.add_app_launcher_args(parser)
args_cli, remaining_argv = parser.parse_known_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

# =============================================================================
# Phase 2: Everything else — safe to import now that the sim is running.
# =============================================================================

import copy
import dataclasses
import importlib
import math
import random
import re
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import gymnasium as gym

# Ensure klask_her is importable (for Actor, Critic, buffer, utils).
_local_klask_her_root = Path(__file__).resolve().parent / "klask_her"
if _local_klask_her_root.exists():
    sys.path.insert(0, str(_local_klask_her_root))

# IsaacLab env registration (triggers gym.register)
import klask_rl.tasks  # noqa: F401
import torch
import torch.nn.functional as F
import tyro
import yaml
from klask_her.agents.fast_sac import Actor, Critic
from klask_her.agents.fast_sac_utils import EmpiricalNormalization, save_params
from klask_her.buffers.gpu_her_replay_buffer import GPUHERReplayBuffer
from klask_rl.tasks.manager_based.klask_rl.actuator_model import ActuatorModelWrapper
from klask_rl.tasks.manager_based.klask_rl.wrappers import (
    FastSACEnvWrapper,
    InitializationWrapper,
    KlaskRlCollisionAvoidanceWrapper,
    VelocityScaleWrapper,
    configure_domain_randomization,
)
from klask_rl.tasks.manager_based.klask_rl.wrappers.klask_rl_ovservation_wrappers import OpponentActionWrapper
from torch.amp import GradScaler, autocast
from torch.utils.tensorboard import SummaryWriter


@dataclass
class PoolEntry:
    """Opponent pool entry with win-rate tracking."""

    state_dict: dict[str, torch.Tensor]
    birth_step: int
    wins: int = 0
    losses: int = 0
    draws: int = 0
    protected: bool = False


def pool_win_rate(entry: PoolEntry) -> float:
    """Win rate against this opponent (default 0.5 if < 10 games played)."""
    total = entry.wins + entry.losses + entry.draws
    return entry.wins / total if total >= 10 else 0.5


@dataclass(frozen=True)
class KlaskTrainingConfig:
    """Full training configuration. CLI flags auto-generated by tyro."""

    # --- Environment ---
    num_envs: int = 16384
    episode_length_s: float = 10.0
    """Episode duration in seconds."""
    goal_reward: float = 1000.0
    """Reward magnitude for goal scored / conceded / peg-in-goal events."""

    # --- HER buffer ---
    buffer_size: int = 2000
    """Per-environment replay buffer capacity."""
    her_ratio: float = 0.0
    goal_radius: float = 0.015
    max_future_steps: int = 300
    contact_priority: float = 0.8
    mirror_y: bool = True

    # --- FastSAC ---
    num_learning_iterations: int = 500_000
    batch_size: int = 32768
    """Global batch size (split across envs during sampling)."""
    num_updates: int = 8
    """Gradient updates per environment step."""
    policy_frequency: int = 4
    """Actor update every N critic updates."""
    learning_starts: int = 10
    """Iterations before training begins."""
    gamma: float = 0.99
    tau: float = 0.125
    actor_hidden_dim: int = 512
    critic_hidden_dim: int = 512
    actor_lr: float = 3e-4
    critic_lr: float = 3e-4
    alpha_lr: float = 3e-4
    alpha_init: float = 0.001
    num_atoms: int = 101
    v_min: float = -1100.0
    v_max: float = 1100.0
    use_autotune: bool = True
    do_compile: bool = True
    amp: bool = True
    amp_dtype: str = "bf16"
    obs_normalization: bool = True
    weight_decay: float = 0.001

    # --- Environment dynamics (parity with train_klask.py PPO pipeline) ---
    sim_dt: float = 0.001
    """Physics step (s)."""
    decimation: int = 20
    """Sim steps per env step."""
    ball_reset_x: tuple[float, float] = (-0.15, 0.15)
    """Ball reset X range (m)."""
    ball_reset_y: tuple[float, float] = (-0.1, -0.04)
    """Ball reset Y range (m). Matches PPO config (narrower than env default)."""
    max_velocity: float = 0.4
    """Peg velocity scale (m/s); maps policy [-1, 1] -> [-max_velocity, max_velocity]."""
    max_acceleration: float | None = 10.0
    """Peg acceleration cap (m/s^2). None to disable rate limiting."""

    # --- Actuator model ---
    enable_actuator_model: bool = True
    """Wrap the env with the learned actuator model (sim-to-real transfer)."""
    actuator_model_checkpoint: str = (
        "/workspace/klask_rl/logs/actuator_model/data/new/checkpoints/"
        "model_data_odrive_new_estimator_history_10_interval_0.02_delay_0.0_"
        "horizon3_with_states_train_seed0.pt"
    )

    # --- Collision avoidance ---
    enable_collision_avoidance: bool = True
    """Innermost wrapper that decelerates pegs near board edges (world-frame m/s)."""

    # --- Initialization schedule ---
    enable_initialization: bool = False
    """Apply InitializationWrapper to set env.unwrapped._init_velocity_speed."""
    init_velocity_speed: float = 1.0
    """Constant init speed when initialization is on. (PPO uses a 3-phase schedule via YAML; SAC uses a constant.)"""

    # --- Self-play ---
    self_play: bool = True
    opponent_pool_size: int = 200
    opponent_save_interval: int = 1_000
    opponent_update_interval: int = 200
    pfsp_epsilon: float = 0.1
    pfsp_p: float = 0.0
    opponent_anchor_steps: tuple[int, ...] = (
        1_000,
        5_000,
        10_000,
        25_000,
        50_000,
        75_000,
        100_000,
        150_000,
        200_000,
        300_000,
        400_000,
    )

    # --- Logging & saving ---
    seed: int = 0
    output_dir: str = "logs/fast_sac_isaaclab/training/${now:%Y-%m-%d}/${now:%H-%M-%S}"
    logging_interval: int = 10
    save_interval: int = 1000
    device: str = "cuda:0"


# --------------------------------------------------------------------------
# Update functions (identical to train_fast_sac.py)
# --------------------------------------------------------------------------


def update_critic(
    data,
    actor,
    qnet,
    qnet_target,
    q_optimizer,
    alpha_optimizer,
    log_alpha,
    target_entropy,
    scaler,
    config,
    device,
    amp_dtype,
):
    """Distributional critic update + entropy autotune."""
    with autocast(device_type="cuda", dtype=amp_dtype, enabled=config.amp):
        next_observations = data["next"]["observations"]
        critic_observations = data["critic_observations"]
        next_critic_observations = data["next"]["critic_observations"]
        actions = data["actions"]
        rewards = data["next"]["rewards"]
        dones = data["next"]["dones"].bool()
        truncations = data["next"]["truncations"].bool()
        bootstrap = (truncations | ~dones).float()

        with torch.no_grad():
            next_actions, next_log_probs = actor.get_actions_and_log_probs(next_observations)
            discount = config.gamma ** data["next"]["effective_n_steps"]
            target_distributions = qnet_target.projection(
                next_critic_observations,
                next_actions,
                rewards - discount * bootstrap * log_alpha.exp() * next_log_probs,
                bootstrap,
                discount,
            )

        q_outputs = qnet(critic_observations, actions)
        critic_log_probs = F.log_softmax(q_outputs, dim=-1)
        critic_losses = -torch.sum(target_distributions * critic_log_probs, dim=-1)
        qf_loss = critic_losses.mean(dim=1).sum(dim=0)

    q_optimizer.zero_grad(set_to_none=True)
    scaler.scale(qf_loss).backward()
    scaler.unscale_(q_optimizer)
    scaler.step(q_optimizer)
    scaler.update()

    alpha_loss = torch.tensor(0.0, device=device)
    if config.use_autotune:
        alpha_optimizer.zero_grad(set_to_none=True)
        with autocast(device_type="cuda", dtype=amp_dtype, enabled=config.amp):
            alpha_loss = (-log_alpha.exp() * (next_log_probs.detach() + target_entropy)).mean()
        scaler.scale(alpha_loss).backward()
        scaler.unscale_(alpha_optimizer)
        scaler.step(alpha_optimizer)
        scaler.update()

    return qf_loss.detach(), alpha_loss.detach(), rewards.mean().detach()


def update_actor(data, actor, qnet, actor_optimizer, log_alpha, scaler, config, amp_dtype):
    """Actor update: maximize Q - alpha * log_prob."""
    with autocast(device_type="cuda", dtype=amp_dtype, enabled=config.amp):
        critic_observations = data["critic_observations"]
        actions, log_probs = actor.get_actions_and_log_probs(data["observations"])
        q_outputs = qnet(critic_observations, actions)
        q_probs = F.softmax(q_outputs, dim=-1)
        q_values = qnet.get_value(q_probs)
        qf_value = q_values.mean(dim=0)
        actor_loss = (log_alpha.exp().detach() * log_probs - qf_value).mean()

    actor_optimizer.zero_grad(set_to_none=True)
    scaler.scale(actor_loss).backward()
    scaler.unscale_(actor_optimizer)
    scaler.step(actor_optimizer)
    scaler.update()
    return actor_loss.detach()


_NOW_PATTERN = re.compile(r"\$\{now:([^}]*)\}")


def resolve_now_placeholders(template: str, now: datetime | None = None) -> str:
    """Expand Hydra-style ``${now:FMT}`` placeholders using ``datetime.strftime``."""
    now = now or datetime.now()
    return _NOW_PATTERN.sub(lambda m: now.strftime(m.group(1)), template)


# --------------------------------------------------------------------------
# Environment creation
# --------------------------------------------------------------------------


def make_isaaclab_env(config: KlaskTrainingConfig) -> FastSACEnvWrapper:
    """Create and configure the IsaacLab Klask environment.

    Wrapper chain mirrors train_klask.py (PPO) so the two pipelines apply the
    same action scaling, reset distribution, and dynamics. Reward curriculum,
    observation noise, action history, and OpponentObservationWrapper are
    intentionally not applied (SAC uses simple goal rewards and its own
    in-script self-play opponent).
    """
    gym_id = "Klask-Rl-FastSAC-v0"

    # Resolve the env config class and instantiate it
    env_cfg_entry = gym.spec(gym_id).kwargs["env_cfg_entry_point"]
    module_name, class_name = env_cfg_entry.rsplit(":", 1)
    env_cfg_class = getattr(importlib.import_module(module_name), class_name)
    env_cfg = env_cfg_class()

    # --- Pre-construction overrides (mirrors train_klask.py:179-202) ---
    env_cfg.scene.num_envs = config.num_envs
    env_cfg.sim.dt = config.sim_dt
    env_cfg.decimation = config.decimation
    env_cfg.episode_length_s = config.episode_length_s
    env_cfg.ball_reset_position_x = tuple(config.ball_reset_x)
    env_cfg.ball_reset_position_y = tuple(config.ball_reset_y)
    env_cfg.events.reset_ball_position.params["pose_range"]["x"] = env_cfg.ball_reset_position_x
    env_cfg.events.reset_ball_position.params["pose_range"]["y"] = env_cfg.ball_reset_position_y

    # All-disabled DR matches the PPO yaml; same hook in case it's enabled later.
    configure_domain_randomization(
        env_cfg,
        {
            "ball_mass": {"enable": False},
            "material_ball": {"enable": False},
            "material_board": {"enable": False},
            "material_peg": {"enable": False},
            "actuator": {"enable": False},
        },
    )

    # Set reward weights: ±goal_reward for terminal events.
    # IsaacLab's RewardManager multiplies each term by step_dt, so we
    # pre-divide here to keep the actual per-step reward equal to
    # ``goal_reward`` (matches the MuJoCo Warp pipeline, which has no
    # dt scaling, and matches the critic's [v_min, v_max] range).
    step_dt = config.sim_dt * config.decimation
    env_cfg.rewards.goal_scored.weight = config.goal_reward / step_dt
    env_cfg.rewards.goal_conceded.weight = -config.goal_reward / step_dt
    env_cfg.rewards.player_in_goal.weight = -config.goal_reward / step_dt
    env_cfg.rewards.opponent_in_goal.weight = config.goal_reward / step_dt

    # The gym registration uses FastSACManagerBasedRLEnv as entry_point,
    # so terminal observations are captured before auto-reset.
    isaac_env = gym.make(
        gym_id,
        cfg=env_cfg,
        render_mode=None,
    )

    # Action-manager pass-through: VelocityScaleWrapper owns [-1, 1] -> m/s.
    for term in isaac_env.unwrapped.action_manager._terms.values():
        term._scale = 1.0

    # --- Wrapper chain (innermost -> outermost), mirrors train_klask.py:232-294 ---

    # 0. Collision avoidance (innermost; world-frame m/s clipping).
    #    Inside OpponentActionWrapper so it sees world-frame actions.
    if config.enable_collision_avoidance:
        isaac_env = KlaskRlCollisionAvoidanceWrapper(
            isaac_env,
            max_vel=float(config.max_velocity),
            peg1_idx=slice(4, 6),  # FastSAC: own_pos
            peg2_idx=slice(6, 8),  # FastSAC: other_pos
        )

    # 1. Opponent action frame transform (ego -> world; negates opponent dims).
    isaac_env = OpponentActionWrapper(isaac_env)

    # 2. Actuator model (m/s in, m/s out). Must sit inside VelocityScaleWrapper
    #    so it sees physical units, not [-1, 1].
    if config.enable_actuator_model:
        isaac_env = ActuatorModelWrapper(
            isaac_env,
            model_file=config.actuator_model_checkpoint,
            pos_idx=slice(4, 6),  # FastSAC: own_pos
            vel_idx=slice(8, 10),  # FastSAC: own_vel
        )

    # 3. Velocity scaling: [-1, 1] (policy output) -> [-max_velocity, max_velocity] m/s.
    act_space = isaac_env.unwrapped.single_action_space
    isaac_env = VelocityScaleWrapper(
        isaac_env,
        max_velocity=float(config.max_velocity),
        max_acceleration=None if config.max_acceleration is None else float(config.max_acceleration),
        num_envs=int(isaac_env.unwrapped.num_envs),
        action_dim=int(act_space.shape[0]),
        device=isaac_env.unwrapped.device,
    )

    # 4. Initialization (sets env.unwrapped._init_velocity_speed for the event manager).
    if config.enable_initialization:
        isaac_env = InitializationWrapper(
            isaac_env,
            {"init_velocity": {"type": "static", "speed": config.init_velocity_speed}},
        )

    # 5. FastSAC adapter (outermost).
    return FastSACEnvWrapper(isaac_env)


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------


def main():
    # Re-inject remaining_argv so tyro sees only the non-AppLauncher flags.
    sys.argv = [sys.argv[0]] + remaining_argv
    config = tyro.cli(KlaskTrainingConfig)
    device = torch.device(config.device)
    amp_dtype = {"bf16": torch.bfloat16, "fp16": torch.float16}[config.amp_dtype] if config.amp else torch.float32

    # Seed
    torch.manual_seed(config.seed)

    # Output directory: resolve ${now:FMT} placeholders to a single timestamp
    # captured here so the date/time stamp is consistent across all paths.
    resolved_output_dir = resolve_now_placeholders(config.output_dir)
    output_dir = Path(resolved_output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    saved_config = dataclasses.asdict(config)
    saved_config["output_dir"] = resolved_output_dir
    with open(output_dir / "config.yaml", "w") as f:
        yaml.safe_dump(saved_config, f)
    writer = SummaryWriter(log_dir=str(output_dir / "tb"))

    # --- Environment ---
    env = make_isaaclab_env(config)
    obs_dim = env.obs_dim
    # Actor controls 2 dims (player X, Y); full action is 4-dim for self-play
    act_dim = 2

    print(
        f"[INFO] IsaacLab env: obs_dim={obs_dim}, env_act_dim={env.act_dim}, "
        f"actor_act_dim={act_dim}, num_envs={env.num_envs}"
    )

    # --- Replay buffer (IsaacLab coords: X=short/symmetric, Y=long/playing) ---
    buffer = GPUHERReplayBuffer(
        num_envs=config.num_envs,
        buffer_size=config.buffer_size,
        obs_dim=obs_dim,
        act_dim=act_dim,
        device=config.device,
        her_ratio=config.her_ratio,
        goal_radius=config.goal_radius,
        goal_reward=config.goal_reward,
        max_future_steps=config.max_future_steps,
        contact_priority=config.contact_priority,
        mirror_y=config.mirror_y,
        # IsaacLab coord system: X=short axis (mirror), Y=long axis (playing)
        mirror_even=True,  # negate even (X) indices for symmetry
        opponent_ball_idx=1,  # ball Y component for opponent-half filter
        opponent_ball_positive=True,  # opponent half is +Y in IsaacLab
    )

    # --- Networks ---
    actor = Actor(
        obs_dim=obs_dim,
        act_dim=act_dim,
        hidden_dim=config.actor_hidden_dim,
        action_scale=1.0,
        device=device,
    ).to(device)
    critic = Critic(
        obs_dim=obs_dim,
        act_dim=act_dim,
        hidden_dim=config.critic_hidden_dim,
        num_atoms=config.num_atoms,
        v_min=config.v_min,
        v_max=config.v_max,
        device=device,
    ).to(device)
    critic_target = copy.deepcopy(critic)

    # Entropy coefficient (learnable)
    log_alpha = torch.tensor([math.log(config.alpha_init)], requires_grad=True, device=device)
    target_entropy = -act_dim

    # Observation normalizer
    obs_normalizer = EmpiricalNormalization(obs_dim, device=device)

    # --- Optimizers ---
    actor_optimizer = torch.optim.AdamW(actor.parameters(), lr=config.actor_lr, weight_decay=config.weight_decay)
    q_optimizer = torch.optim.AdamW(critic.parameters(), lr=config.critic_lr, weight_decay=config.weight_decay)
    alpha_optimizer = torch.optim.AdamW([log_alpha], lr=config.alpha_lr)
    scaler = GradScaler("cuda", enabled=config.amp)

    # --- Optional torch.compile ---
    _update_critic = update_critic
    _update_actor = update_actor
    _explore = actor.explore
    if config.do_compile:
        _update_critic = torch.compile(update_critic)
        _update_actor = torch.compile(update_actor)
        _explore = torch.compile(actor.explore)

    # --- Self-play opponent ---
    if config.self_play:
        opponent_actor = copy.deepcopy(actor)
        opponent_actor.eval()
        anchor_steps_set = set(config.opponent_anchor_steps)
        opponent_pool: list[PoolEntry] = [
            PoolEntry(
                state_dict={k: v.detach().clone() for k, v in actor.state_dict().items()},
                birth_step=0,
                protected=True,
            )
        ]
        current_opponent_idx = 0
        current_opp_wins = 0
        current_opp_losses = 0
        current_opp_draws = 0

    # --- Training loop ---
    reset_out = env.reset_all()
    if isinstance(reset_out, tuple):
        obs, opp_obs_init = reset_out
    else:
        obs, opp_obs_init = reset_out, None
    opp_obs = opp_obs_init if config.self_play else None
    infos: dict = {}
    total_goals = 0
    total_own_goals = 0
    total_peg1_in_goal = 0
    total_peg2_in_goal = 0
    total_episodes = 0
    total_contact_episodes = 0
    ep_had_contact = torch.zeros(config.num_envs, dtype=torch.bool, device=device)
    ep_reward_sum = torch.zeros(config.num_envs, device=device)
    t0 = time.time()

    per_env_batch = max(config.batch_size // config.num_envs, 1)

    print(f"Training FastSAC+HER (IsaacLab) | {config.num_envs} envs | {config.num_learning_iterations} iters")
    print(f"Output: {output_dir}")

    for step in range(1, config.num_learning_iterations + 1):
        # --- Collect ---
        with torch.no_grad():
            norm_obs = obs_normalizer(obs, update=True)
            actions = _explore(norm_obs)

        if config.self_play:
            # Use IsaacLab's opponent observation group (already mirrored/rotated)
            opp_norm = obs_normalizer(opp_obs, update=False)
            with torch.no_grad():
                a2_mirrored = opponent_actor.explore(opp_norm)
            # Pass opponent actions in player frame — OpponentActionWrapper handles
            # the 180° rotation back to world frame before the env sees them.
            full_actions = torch.cat([actions, a2_mirrored], dim=-1)
            next_obs, rewards, dones, infos = env.step(full_actions)
        else:
            next_obs, rewards, dones, infos = env.step(actions)
        ep_reward_sum += rewards

        # Store final_obs for ALL done envs (preserves ball position for HER)
        true_next_obs = torch.where(
            dones.unsqueeze(-1) > 0,
            infos["final_obs"],
            next_obs,
        )
        buffer.extend(
            obs=obs,
            next_obs=true_next_obs,
            actions=actions,
            rewards=rewards,
            dones=dones,
            truncations=infos["time_outs"],
            ball_peg_contact=infos["ball_peg_contact"],
        )
        obs = next_obs
        if config.self_play and "opponent_obs" in infos:
            opp_obs = infos["opponent_obs"]

        # Episode stats
        ep_had_contact |= infos["ball_peg_contact"]
        if dones.any():
            done_ids = dones.nonzero(as_tuple=False).flatten()
            n_done = done_ids.numel()
            total_episodes += n_done
            total_goals += infos["goal_scored"][done_ids].sum().item()
            total_own_goals += infos["own_goal"][done_ids].sum().item()
            total_peg1_in_goal += infos["peg1_in_goal"][done_ids].sum().item()
            total_peg2_in_goal += infos["peg2_in_goal"][done_ids].sum().item()
            total_contact_episodes += ep_had_contact[done_ids].sum().item()
            if config.self_play:
                wins = (infos["goal_scored"][done_ids] | infos["peg2_in_goal"][done_ids]).sum().item()
                losses = (infos["own_goal"][done_ids] | infos["peg1_in_goal"][done_ids]).sum().item()
                current_opp_wins += wins
                current_opp_losses += losses
                current_opp_draws += n_done - wins - losses
            ep_had_contact[done_ids] = False
            ep_reward_sum[done_ids] = 0.0

        # --- Update ---
        if step > config.learning_starts:
            large_batch = buffer.sample(per_env_batch * config.num_updates)
            large_batch["observations"] = obs_normalizer(large_batch["observations"], update=False)
            large_batch["next"]["observations"] = obs_normalizer(large_batch["next"]["observations"], update=False)
            large_batch["critic_observations"] = large_batch["observations"]
            large_batch["next"]["critic_observations"] = large_batch["next"]["observations"]

            samples_per_update = per_env_batch * config.num_envs
            for i in range(config.num_updates):
                s = i * samples_per_update
                e = s + samples_per_update
                mini = {
                    "observations": large_batch["observations"][s:e],
                    "actions": large_batch["actions"][s:e],
                    "critic_observations": large_batch["critic_observations"][s:e],
                    "next": {
                        "observations": large_batch["next"]["observations"][s:e],
                        "critic_observations": large_batch["next"]["critic_observations"][s:e],
                        "rewards": large_batch["next"]["rewards"][s:e],
                        "dones": large_batch["next"]["dones"][s:e],
                        "truncations": large_batch["next"]["truncations"][s:e],
                        "effective_n_steps": large_batch["next"]["effective_n_steps"][s:e],
                    },
                }

                qf_loss, alpha_loss, buf_rewards = _update_critic(
                    mini,
                    actor,
                    critic,
                    critic_target,
                    q_optimizer,
                    alpha_optimizer,
                    log_alpha,
                    target_entropy,
                    scaler,
                    config,
                    device,
                    amp_dtype,
                )

                if config.num_updates > 1:
                    do_actor = i % config.policy_frequency == 1
                else:
                    do_actor = step % config.policy_frequency == 0
                if do_actor:
                    _update_actor(
                        mini,
                        actor,
                        critic,
                        actor_optimizer,
                        log_alpha,
                        scaler,
                        config,
                        amp_dtype,
                    )

                # Soft target update
                with torch.no_grad():
                    src_ps = [p.data for p in critic.parameters()]
                    tgt_ps = [p.data for p in critic_target.parameters()]
                    torch._foreach_mul_(tgt_ps, 1.0 - config.tau)
                    torch._foreach_add_(tgt_ps, src_ps, alpha=config.tau)

        # --- Logging ---
        if step % config.logging_interval == 0:
            elapsed = time.time() - t0
            sps = step * config.num_envs / elapsed
            goal_rate = total_goals / max(total_episodes, 1)
            own_goal_rate = total_own_goals / max(total_episodes, 1)
            p1ig_rate = total_peg1_in_goal / max(total_episodes, 1)
            p2ig_rate = total_peg2_in_goal / max(total_episodes, 1)
            contact_rate = total_contact_episodes / max(total_episodes, 1)
            writer.add_scalar("perf/steps_per_sec", sps, step)
            writer.add_scalar("perf/total_episodes", total_episodes, step)
            writer.add_scalar("episode/goal_rate", goal_rate, step)
            writer.add_scalar("episode/own_goal_rate", own_goal_rate, step)
            writer.add_scalar("episode/peg1_in_goal_rate", p1ig_rate, step)
            writer.add_scalar("episode/peg2_in_goal_rate", p2ig_rate, step)
            writer.add_scalar("episode/contact_rate", contact_rate, step)
            writer.add_scalar("her/relabel_frac", buffer.her_relabel_frac, step)
            writer.add_scalar("her/scored_frac", buffer.her_scored_frac, step)
            writer.add_scalar("her/contact_frac", buffer.her_contact_sample_frac, step)
            writer.add_scalar("train/alpha", log_alpha.exp().item(), step)
            if step > config.learning_starts:
                writer.add_scalar("train/critic_loss", qf_loss.item(), step)
                writer.add_scalar("train/alpha_loss", alpha_loss.item(), step)
                writer.add_scalar("train/buffer_rewards", buf_rewards.item(), step)
            if config.self_play:
                writer.add_scalar("self_play/pool_size", len(opponent_pool), step)
                wrs = [pool_win_rate(e) for e in opponent_pool]
                writer.add_scalar("self_play/mean_win_rate", sum(wrs) / len(wrs), step)
                writer.add_scalar("self_play/min_win_rate", min(wrs), step)
                writer.add_scalar("self_play/max_win_rate", max(wrs), step)
                writer.add_scalar(
                    "self_play/current_opp_birth_step", opponent_pool[current_opponent_idx].birth_step, step
                )
                writer.add_scalar(
                    "self_play/current_opp_win_rate", pool_win_rate(opponent_pool[current_opponent_idx]), step
                )
                writer.add_scalar("self_play/num_protected", sum(1 for e in opponent_pool if e.protected), step)
            if step % (config.logging_interval * 10) == 0:
                print(
                    f"[{step:>7d}] sps={sps:.0f} eps={total_episodes} "
                    f"goals={total_goals} og={total_own_goals} p1ig={total_peg1_in_goal} p2ig={total_peg2_in_goal} "
                    f"rate={goal_rate:.3f} og_rate={own_goal_rate:.3f} "
                    f"contact={contact_rate:.3f} alpha={log_alpha.exp().item():.4f}"
                )

        # --- Opponent pool: save snapshot ---
        if config.self_play and step % config.opponent_save_interval == 0:
            is_anchor = step in anchor_steps_set
            snapshot = PoolEntry(
                state_dict={k: v.detach().clone() for k, v in actor.state_dict().items()},
                birth_step=step,
                protected=is_anchor,
            )
            opponent_pool.append(snapshot)
            if len(opponent_pool) > config.opponent_pool_size:
                candidates = [(i, e) for i, e in enumerate(opponent_pool) if not e.protected]
                if candidates:
                    evict_idx = max(candidates, key=lambda x: pool_win_rate(x[1]))[0]
                    opponent_pool.pop(evict_idx)
                    if current_opponent_idx >= evict_idx:
                        current_opponent_idx = max(0, current_opponent_idx - 1)

        # --- Opponent pool: decay stale win-rate stats ---
        if config.self_play and step % 10_000 == 0:
            for e in opponent_pool:
                if e.wins + e.losses + e.draws > 100:
                    e.wins //= 2
                    e.losses //= 2
                    e.draws //= 2

        # --- Opponent pool: PFSP swap active opponent ---
        if config.self_play and step % config.opponent_update_interval == 0:
            opponent_pool[current_opponent_idx].wins += current_opp_wins
            opponent_pool[current_opponent_idx].losses += current_opp_losses
            opponent_pool[current_opponent_idx].draws += current_opp_draws
            current_opp_wins = current_opp_losses = current_opp_draws = 0
            weights = [(1.0 - pool_win_rate(e) + config.pfsp_epsilon) ** config.pfsp_p for e in opponent_pool]
            current_opponent_idx = random.choices(range(len(opponent_pool)), weights=weights, k=1)[0]
            opponent_actor.load_state_dict(opponent_pool[current_opponent_idx].state_dict)

        # --- Checkpoint ---
        if config.save_interval > 0 and step % config.save_interval == 0:
            save_params(
                global_step=step,
                actor=actor,
                qnet=critic,
                qnet_target=critic_target,
                log_alpha=log_alpha,
                obs_normalizer=obs_normalizer,
                actor_optimizer=actor_optimizer,
                q_optimizer=q_optimizer,
                alpha_optimizer=alpha_optimizer,
                scaler=scaler,
                config=config,
                save_path=str(output_dir / f"model_{step:07d}.pt"),
            )

    # Final save
    save_params(
        global_step=config.num_learning_iterations,
        actor=actor,
        qnet=critic,
        qnet_target=critic_target,
        log_alpha=log_alpha,
        obs_normalizer=obs_normalizer,
        actor_optimizer=actor_optimizer,
        q_optimizer=q_optimizer,
        alpha_optimizer=alpha_optimizer,
        scaler=scaler,
        config=config,
        save_path=str(output_dir / "model_final.pt"),
    )
    writer.close()
    simulation_app.close()
    print(f"Training complete. {total_episodes} episodes, {total_goals} goals.")


if __name__ == "__main__":
    main()
