defaults:
  logdir: null
  traindir: null
  evaldir: null
  offline_traindir: ''
  offline_evaldir: ''
  seed: 0
  deterministic_run: False
  steps: 1e6
  parallel: False
  eval_every: 1e4
  eval_episode_num: 10
  log_every: 1e4
  reset_every: 0
  device: 'cuda:0'
  compile: True
  precision: 32
  debug: False
  video_pred_log: True

  # Environment
  task: ''
  size: [64, 64]
  envs: 1
  action_repeat: 2
  time_limit: 1000
  grayscale: False
  prefill: 2500
  reward_EMA: True

  # Model
  dyn_hidden: 512
  dyn_deter: 512
  dyn_stoch: 32
  dyn_discrete: 32
  dyn_rec_depth: 1
  dyn_mean_act: 'none'
  dyn_std_act: 'sigmoid2'
  dyn_min_std: 0.1
  grad_heads: ['decoder', 'reward', 'cont']
  units: 512
  act: 'SiLU'
  norm: True
  encoder:
    {
      mlp_keys: '$^',
      cnn_keys: 'image',
      act: 'SiLU',
      norm: True,
      cnn_depth: 32,
      kernel_size: 4,
      minres: 4,
      mlp_layers: 5,
      mlp_units: 1024,
      symlog_inputs: True,
    }
  decoder:
    {
      mlp_keys: '$^',
      cnn_keys: 'image',
      act: 'SiLU',
      norm: True,
      cnn_depth: 32,
      kernel_size: 4,
      minres: 4,
      mlp_layers: 5,
      mlp_units: 1024,
      cnn_sigmoid: False,
      image_dist: mse,
      vector_dist: symlog_mse,
      outscale: 1.0,
    }
  actor:
    {
      layers: 2,
      dist: 'normal',
      entropy: 3e-4,
      unimix_ratio: 0.01,
      std: 'learned',
      min_std: 0.1,
      max_std: 1.0,
      temp: 0.1,
      lr: 3e-5,
      eps: 1e-5,
      grad_clip: 100.0,
      outscale: 1.0,
    }
  critic:
    {
      layers: 2,
      dist: 'symlog_disc',
      slow_target: True,
      slow_target_update: 1,
      slow_target_fraction: 0.02,
      lr: 3e-5,
      eps: 1e-5,
      grad_clip: 100.0,
      outscale: 0.0,
    }
  reward_head:
    { layers: 2, dist: 'symlog_disc', loss_scale: 1.0, outscale: 0.0 }
  cont_head: { layers: 2, loss_scale: 1.0, outscale: 1.0 }
  dyn_scale: 0.5
  rep_scale: 0.1
  kl_free: 1.0
  weight_decay: 0.0
  unimix_ratio: 0.01
  initial: 'learned'

  # Training
  batch_size: 16
  batch_length: 64
  train_ratio: 512
  pretrain: 100
  model_lr: 1e-4
  opt_eps: 1e-8
  grad_clip: 1000
  dataset_size: 1000000
  opt: 'adam'

  # Behavior.
  discount: 0.997
  discount_lambda: 0.95
  imag_horizon: 15
  imag_gradient: 'dynamics'
  imag_gradient_mix: 0.0
  eval_state_mean: False

  # Exploration
  expl_behavior: 'greedy'
  expl_until: 0
  expl_extr_scale: 0.0
  expl_intr_scale: 1.0
  disag_target: 'stoch'
  disag_log: True
  disag_models: 10
  disag_offset: 1
  disag_layers: 4
  disag_units: 400
  disag_action_cond: False

klask_vision_rgb:
  # Environment
  task: Klask-Rl-Dreamer-v0
  envs: 4
  action_repeat: 20
  max_velocity: 0.6 # [m/s] Maximum velocity for player movement
  episode_length_s: 4.0 # [s] Episode length in seconds
  actuator_model: true

  # Model
  size: [64, 64] # has to be 2^n and quare due to the CNN architecture
  encoder: { mlp_keys: '$^', cnn_keys: 'image' }
  decoder: { mlp_keys: '$^', cnn_keys: 'image' }

  # Training
  steps: 5e5
  train_ratio: 512
  video_pred_log: true

  rewards:
    time_punishment: 0.0
    time_out_punishment: 0.0
    shot_over_middle_line: 0.0
    player_in_goal: -3.0
    opponent_in_goal: 0.0
    goal_scored: 5.0
    goal_conceded: -3.0
    distance_player_ball_own_half: 0.0
    distance_ball_opponent_goal: 10.1
    distance_ball_own_goal: -10.1
    ball_speed: 0.0
    ball_stationary: -0.01
    collision_player_ball: 0.5
    ball_in_own_half: 0.0
    close_to_boundaries: -0.01
    player_strategically_positioned: 0.0

  terminations:
    time_out: true
    goal_scored: true
    goal_conceded: true
    player_in_goal: true
    opponent_in_goal: true

  # Logging
  logdir: null # if log dir is set to a non empty directory the training will continue from the latest checkpoint in that directory
  wandb_project: KLASK_Dreamer
  wandb_entity: null
  wandb_name: dreamer_vision_rgb

debug:
  debug: True
  pretrain: 1
  prefill: 1
  batch_size: 10
  batch_length: 20
